# Windows build

name: windows

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  merge_group:

env:
  TOOL_CHAIN: "1.82"

jobs:
  check-reth:
    runs-on: ubuntu-20.04
    timeout-minutes: 60

    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          target: x86_64-pc-windows-gnu
          toolchain: ${{ env.TOOL_CHAIN }}
      - uses: taiki-e/install-action@cross
      - uses: Swatinem/rust-cache@v2
        with:
          cache-on-failure: true
      - name: mingw-w64
        run: sudo apt-get install -y mingw-w64
      - name: Check Reth
        run: cargo check --target x86_64-pc-windows-gnu

  check-op-reth:
    runs-on: ubuntu-20.04
    timeout-minutes: 60

    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          target: x86_64-pc-windows-gnu
          toolchain: ${{ env.TOOL_CHAIN }}
      - uses: taiki-e/install-action@cross
      - uses: Swatinem/rust-cache@v2
        with:
          cache-on-failure: true
      - name: mingw-w64
        run: sudo apt-get install -y mingw-w64
      - name: Check OP-Reth
        run: cargo check -p op-reth --features "optimism opbnb" --target x86_64-pc-windows-gnu

  check-bsc-reth:
    runs-on: ubuntu-20.04
    timeout-minutes: 60

    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          target: x86_64-pc-windows-gnu
          toolchain: ${{ env.TOOL_CHAIN }}
      - uses: taiki-e/install-action@cross
      - uses: Swatinem/rust-cache@v2
        with:
          cache-on-failure: true
      - name: mingw-w64
        run: sudo apt-get install -y mingw-w64
      - name: Check Bsc-Reth
        run: cargo check -p bsc-reth --features "bsc" --target x86_64-pc-windows-gnu
